apiVersion: v1
kind: Namespace
metadata:
  name: error-testing
  labels:
    purpose: testing
    environment: development

---
# Scenario 1: CrashLoopBackOff - App crashes after 10 requests
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-app
  namespace: error-testing
  labels:
    app: crashloop
    scenario: crashloopbackoff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crashloop
  template:
    metadata:
      labels:
        app: crashloop
    spec:
      containers:
      - name: nodejs-app
        image: error-generator:latest
        imagePullPolicy: Never
        env:
        - name: ERROR_TYPE
          value: "panic"
        - name: ERROR_RATE
          value: "0.3"
        - name: CRASH_AFTER
          value: "10"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
# Scenario 2: OOMKilled - Memory leak causes OOM
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-app
  namespace: error-testing
  labels:
    app: oom
    scenario: oomkilled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom
  template:
    metadata:
      labels:
        app: oom
    spec:
      containers:
      - name: python-app
        image: python-error-generator:latest
        imagePullPolicy: Never
        env:
        - name: ERROR_TYPE
          value: "none"
        - name: OOM_TRIGGER
          value: "true"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"  # Low limit to trigger OOM faster
            cpu: "100m"

---
# Scenario 3: High error rate app (lots of errors in logs)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-spammer
  namespace: error-testing
  labels:
    app: error-spammer
    scenario: high-error-rate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: error-spammer
  template:
    metadata:
      labels:
        app: error-spammer
    spec:
      containers:
      - name: nodejs-app
        image: error-generator:latest
        imagePullPolicy: Never
        env:
        - name: ERROR_TYPE
          value: "connection"
        - name: ERROR_RATE
          value: "0.8"  # 80% error rate
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
# Scenario 4: Unhealthy pod (failing health checks)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unhealthy-app
  namespace: error-testing
  labels:
    app: unhealthy
    scenario: failing-health-check
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unhealthy
  template:
    metadata:
      labels:
        app: unhealthy
    spec:
      containers:
      - name: python-app
        image: python-error-generator:latest
        imagePullPolicy: Never
        env:
        - name: ERROR_TYPE
          value: "unhealthy"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
# Scenario 5: ImagePullBackOff - Invalid image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepull-fail
  namespace: error-testing
  labels:
    app: imagepull-fail
    scenario: imagepullbackoff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepull-fail
  template:
    metadata:
      labels:
        app: imagepull-fail
    spec:
      containers:
      - name: fake-app
        image: nonexistent-registry.io/fake-image:v1.0.0
        ports:
        - containerPort: 3000

---
# Scenario 6: Pending pod (high resource requests)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-app
  namespace: error-testing
  labels:
    app: pending
    scenario: pending-resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pending
  template:
    metadata:
      labels:
        app: pending
    spec:
      containers:
      - name: nodejs-app
        image: error-generator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "100Gi"  # Unreasonably high
            cpu: "50"        # Unreasonably high
          limits:
            memory: "100Gi"
            cpu: "50"

---
# Scenario 7: CPU intensive app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-intensive
  namespace: error-testing
  labels:
    app: cpu-intensive
    scenario: high-cpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-intensive
  template:
    metadata:
      labels:
        app: cpu-intensive
    spec:
      containers:
      - name: nodejs-app
        image: error-generator:latest
        imagePullPolicy: Never
        env:
        - name: CPU_INTENSIVE
          value: "true"
        - name: ERROR_TYPE
          value: "none"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "150m"  # Will hit CPU limit

---
# Scenario 8: Database connection errors
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-error-app
  namespace: error-testing
  labels:
    app: db-error
    scenario: database-errors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-error
  template:
    metadata:
      labels:
        app: db-error
    spec:
      containers:
      - name: python-app
        image: python-error-generator:latest
        imagePullPolicy: Never
        env:
        - name: ERROR_TYPE
          value: "db-error"
        - name: ERROR_RATE
          value: "0.5"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
# Service for error apps
apiVersion: v1
kind: Service
metadata:
  name: error-apps-service
  namespace: error-testing
spec:
  selector:
    app: error-spammer
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP